### ISSUE TITLE
Fails for CRAN package with MIT license

### ISSUE THREAD

**Issue by jonathan-g** [licensee/licensee#185]
The specification for creating [a CRAN project with the MIT license](https://cran.r-project.org/web/licenses/MIT) requires putting the following line in the `DESCRIPTION` file:
```
License: MIT + file LICENSE
``` 
and creating a `LICENSE` file that contains only these two lines:
```
YEAR: <copyright year>
COPYRIGHT HOLDER: <name of copyright holder>
```
Running `licensee` on such a project produces the following incorrect result:
```
License file: LICENSE
License hash: 56a12441c53d08f67a7cd49fa8e03777bbf4d596
```

**Comment by benbalter** [comment]
https://github.com/benbalter/licensee/pull/160 May resolve this.

**Comment by jonathan-g** [comment]
Yes. Looks like that will fix this. I will close this issue for now and re-open if the subsequent release with #160 doesn't fix the problem.

**Comment by jonathan-g** [comment]
This is still failing.

## Failure to detect MIT license with CRAN files:

Using licensee 9.10.1, I run
```
licensee detect --remote https://github.com/jonathan-g/datafsm/
```
or 
```
licensee detect --packages --remote https://github.com/jonathan-g/datafsm/
```
both return the following result:
```
License:        NOASSERTION
Matched files:  LICENSE, LICENSE.md, LICENSE.Rmd, DESCRIPTION
LICENSE:
  Content hash:  949dc60d61d204271bb87f56d025cc4723f3ec9b
  License:       NOASSERTION
LICENSE.md:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright (c) 2015-2018 John Nay and Jonathan Gilligan
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
LICENSE.Rmd:
  Content hash:  36b888aa6702a196a3f07ec982adebc664a33629
  License:       NOASSERTION
DESCRIPTION:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::Cran
  License:     MIT
```
It is surprising to me that even with a 100% match to the MIT license on LICENSE.md and a 90% match to the MIT license on DESCRIPTION, licensee returns NOASSERTION.

I am also puzzled why DESCRIPTION does not yield a 100% match.

## Failure to detect MIT license with LICENSE.spdx

If I add a text file LICENSE.spdx with a single line
```
PackageLicenseDeclared: MIT
```
then `licensee detect` returns
```
License:        NOASSERTION
Matched files:  LICENSE, LICENSE.md, LICENSE.Rmd, LICENSE.spdx
LICENSE:
  Content hash:  949dc60d61d204271bb87f56d025cc4723f3ec9b
  License:       NOASSERTION
LICENSE.md:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright (c) 2015-2018 John Nay and Jonathan Gilligan
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
LICENSE.Rmd:
  Content hash:  36b888aa6702a196a3f07ec982adebc664a33629
  License:       NOASSERTION
LICENSE.spdx:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::Spdx
  License:     MIT
```
Again, I can't figure out why this would not be a 100% match for MIT license in LICENSE.spdx.

## Changing confidence Level does not produce a match

Since I have two files that match with >=90% confidence, I try detecting with `--confidence 85`, but I still get
```
License:        NOASSERTION
Matched files:  LICENSE, LICENSE.md, LICENSE.Rmd, DESCRIPTION
LICENSE:
  Content hash:  949dc60d61d204271bb87f56d025cc4723f3ec9b
  License:       NOASSERTION
LICENSE.md:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright (c) 2015-2018 John Nay and Jonathan Gilligan
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
LICENSE.Rmd:
  Content hash:  36b888aa6702a196a3f07ec982adebc664a33629
  License:       NOASSERTION
  Closest non-matching licenses:
    BSL-1.0 similarity:             62.88%
    Unlicense similarity:           53.28%
    BSD-3-Clause-Clear similarity:  46.91%
DESCRIPTION:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::Cran
  License:     MIT
```
So even though two files match with greater confidence than the specified threshold, the final result is NOASSERTION (using the API in Ruby produces `license.key = "other"`).

## Behavior when multiple possible license files produce different results

If LICENSE.md produces a 100% match with MIT and another file (LICENSE.spdx or DESCRIPTION) produces a 90% match, and all the other files produce NOASSERTION (`"other"` in the Ruby API), I would think the desirable behavior would be to return the MIT license.

However, I may misunderstand your intention with this package, and I understand that it's a subjective judgment to decide the optimal balance between the risk of false-positives against the risk of false-negatives. I also get that licensee is a widely used package, and only a small fraction of its audience develops R packages using the MIT license, so your own priority in working on the package is very likely elsewhere, and for good reasons.

Nonetheless, it would be nice if there were a way for me to configure my repository to tell other people's instances of licensee that I really intend for a project to be licensed just under MIT. 

It's a big pain because of the strict and inflexible requirements at CRAN to use a file that must be called "LICENSE" in a very non-standard manner, but it would be nice if there were a workaround that is not too difficult to implement (e.g., prioritize project files like DESCRIPTION or LICENSE.spdx by default if they are present).

**Comment by mlinksva** [comment]
Licensee only returns an overall project license if it detects the same license in all of the potential license (confidence level determines whether licensee will detect a license in a file above a similarity threshold) and package files (for which [90% is hardcoded](https://github.com/benbalter/licensee/blob/647913341aaf9fea122cbe7113a52aa2ad822dfb/lib/licensee/matchers/package.rb#L14-L16), though I don't think it needs to be at file level) it finds (i.e, it's prioritizing avoiding false positives):

https://github.com/benbalter/licensee/blob/647913341aaf9fea122cbe7113a52aa2ad822dfb/lib/licensee/projects/project.rb#L21-L30

In all of the cases above, it's not detecting a license in a two potential license files (`LICENSE` and `LICENSE.Rmd`) so licensee returns `NOASSERTION` overall.

The easiest thing would be for you @jonathan-g  to rename `LICENSE` and `LICENSE.Rmd`, that is ignoring CRAN requirements. Taking into account CRAN requirements ... first I'm not 100% certain what the requirements are after skimming http://r-pkgs.had.co.nz/description.html#license and https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing ... is there some code that stipulates what the requirements are precisely in practice?

For `LICENSE.Rmd` https://github.com/search?q=filename:LICENSE.Rmd finds 434 such files; I haven't looked further to see whether it could make sense for licensee to avoid treating such files as a license files like

https://github.com/benbalter/licensee/blob/647913341aaf9fea122cbe7113a52aa2ad822dfb/lib/licensee/project_files/license_file.rb#L10-L11

I'd guess it'd be most similar to `.header` -- utility file within some projects -- rather than `.spdx` or .`gemspec` which are looked at by the appropriate licensee package detection code if found.

For `LICENSE` it looks like CRAN wants that to only have copyright year and holder name-values? Conceivably I guess https://github.com/benbalter/licensee/blob/647913341aaf9fea122cbe7113a52aa2ad822dfb/lib/licensee/matchers/copyright.rb could recognize that format though don't whether that's a good idea.

**Comment by jonathan-g** [comment]
Yes. CRAN requires that for the MIT license the DESCRIPTION file has the line
```
License: MIT + file LICENSE
```
and that the file LICENSE consist of two lines:
```
YEAR:
COPYRIGHT HOLDER: 
```
See <https://www.r-project.org/Licenses/MIT> for details.

I agree that this is a very strange way to organize things and that CRAN's way of doing this creates unnecessary difficulty for a package like licensee.

I certainly would not want to ask for changes to accommodate this corner case if they would either be a lot of work for the package maintainers or would potentially cause bigger problems for other users.

**Comment by mlinksva** [comment]
@jonathan-g and what is the reason for LICENSE.Rmd? Does CRAN require that? How is it used, our of curiosity?

https://github.com/benbalter/licensee/blob/d81cc3273403aada1c6314b32bf6cf4c0835e960/lib/licensee/matchers/cran.rb already deals with the DESCRIPTION file and some of its oddities (non-standard license ids, `+ file LICENSE`.

I'm pretty sure the remaining corner case is the LICENSE file itself.
