### ISSUE TITLE
Return SPDX license expressions?

### ISSUE THREAD

**Issue by wking** [licensee/licensee#244]
On Mon, Nov 27, 2017 at 04:10:25PM +0000, Ben Balter [wrote][1]:
>     +  "license": "(MIT OR Apache-2.0 OR AGPL-3.0+)",
>
> It will take some reworking of the logic in the Project class, but in a subsequent iteration, it'd be cool to be able to parse the expression and return multiple licenses, where we can match the SPDX ID.

This also came up in #241:

> Other because licensee doesn't know about `CC-BY-3.0` (only 4.0), nor about `+`.

I'd expect Licensee to return [SPDX license expressions][2] (not just license IDs).  In that case, `package.json` processing would remove/process [npm extentions][3] like `SEE LICENSE IN <filename>` and `UNLICENSED` (although see spdx/spdx-spec#49 about maybe addressing the `UNLICENSED` use case from within license expressions) but would return SPDX license expressions unmodified.  And `LICENSE.spdx` processors could return the declared license expression directly too.

Parsing license expressions might be useful for cases like “`package.json` declares `GPL-2.0` but `COPYING` contains `GPL-3.0`”.  But if `package.json` declares `GPL-2.0+` and `COPYING` contains `GPL-2.0`, I think Licensee should be returning the full `GPL-2.0+`.

[1]: https://github.com/benbalter/licensee/pull/240#pullrequestreview-79219233
[2]: https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60
[3]: https://docs.npmjs.com/files/package.json#license

**Comment by mlinksva** [comment]
👍  the very last case you mention (`+`) is the first I plan to tackle, indeed a recent bump in discussions of `+`, `-only`, etc is what prompted me to stub out #241 which prompted me to look at and notice the missing expression awareness fixed in #240.

General handling of and returning SPDX license expressions would be good eventually though.

**Comment by wking** [comment]
bump

**Comment by wking** [comment]
bump

**Comment by wking** [comment]
bump

**Comment by wking** [comment]
bump

**Comment by jeffmcaffer** [comment]
Does this issue cover the idea of discovering multiple full license texts in one (or several) license files? Has there been any thoughts or work on doing that?

**Comment by mlinksva** [comment]
Licensee already discovers multiple full license texts each in different license files. It can identify the license in each file and reports the license for each file, but NOASSERTION overall because it doesn't know how those licenses relate to each other and the project, e.g., could be the project is dual licensed, could be some material is under one license, some under another.

Multiple license texts in one license file always obtains NOASSERTION. Detecting that there are multiple license texts that can be detected in a single file would be new functionality, probably worth a a separate issue.

The minimum fix for this issue might be for licensee to return a license expression when it finds a valid one in a package manager file (currently something like `MIT AND Apache-2.0` would obtain NOASSERTION).

A fuller, possibly another issue, fix, would be to take a license expression found in a package manager file and use that expression to understand what multiple full license texts mean for a project, e.g., suppose the following files are present and package manager detection is turned on:

- `LICENSE-APACHE` contains Apache-2.0
- `LICNESE-MIT` contains MIT
- `Cargo.toml` contains `license = "MIT OR Apache-2.0"`

Currently, licensee would detect and report each of those licenses individually, but for the project return NOASSERTION. With fuller fix, it would see that the two license files match what is in the license expression and confidently return `MIT OR Apache-2.0`.

**Comment by goneall** [comment]
There may be some judgement required to determine if `AND` or `OR` is appropriate.  Many packages have complete license text for disjunctive license choices for the package.  Other package collect licenses for any embedded licenses and include them in a separate file (e.g. 3rdparty.txt).  Although the former is more common, I don't know if you can be certain the `OR` should be used.

**Comment by mlinksva** [comment]
@goneall that's why I'm only suggesting returning a license expression if one is explicitly provided! If two license files are present without an expression, licensee wouldn't have a way to be confident about whether `AND`, `OR`, `;` 😉 or something else is reality.

**Comment by ale5000-git** [comment]
The support for `+` / `-or-later` is the most imprtant and urgent I think.
