### ISSUE TITLE
Cannot detect the LGPL license

### ISSUE THREAD

**Issue by ale5000-git** [licensee/licensee#287]
Hi,
it would be nice to detect `COPYING.LESSER` and `LICENSE.LESSER` file for the LGPL license.

Example project: https://github.com/ale5000-git/pycompatlayer

The official raccomandation on https://www.gnu.org/licenses/gpl-howto.en.html is:
> - Add a COPYING file with a copy of the GNU GPL or GNU AGPL.
> - Also add a COPYING.LESSER file with a copy of the GNU LGPL, if you use that.
> 
> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs we conventionally put the license in a file called COPYING.
> 
> Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's crucial to include both licenses so users have all the materials they need to understand their rights.

**Comment by benbalter** [comment]
@ale5000-git per the GPL instructions you linked to, the file should be `COPYING.LESSER` not `LICENSE.LESSER`. If you make that change, Licensee should properly identify the LGPL.

**Comment by 1138-4EB** [comment]
@benbalter, I just tried it, and it seems to work with `LICENSE.LESSER` too:
```
/# git clone https://gitlab.com/ale5000-git/pycompatlayer
...
/# cd pycompatlayer/
/pycompatlayer# licensee
License: Other
Matched files: ["LICENSE", "LICENSE.LESSER"]
LICENSE:
  Content hash: f9aaff304edbbe732f27b554dcb6abe49e0b4fa0
  Attribution: Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.or
g/>
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: GNU General Public License v3.0
LICENSE.LESSER:
  Content hash: 43dd63c9f6e1a6f773d1162dade1b307f6b6a6c3
  Attribution: Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.or
g/>
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: GNU Lesser General Public License v3.0
```

**Comment by ale5000-git** [comment]
The problem is that it isn't detected on GitHub, since LGPL is an extension of GPL it should detect that GPL as just "part" of LGPL if also the latter is present and not present it as it would a double license.

**Comment by 1138-4EB** [comment]
Then, I think it might be a bug or missing feature in GitHub, not in licensee. We have seen similar results in other repos where licensee detects more than a single valid license file. See [this](https://github.com/idleberg/Creative-Commons-Markdown/issues/10#issuecomment-379513402) comment. As referred there, the clue can be [this](https://github.com/isaacs/github/issues/1181#issuecomment-366000250) reply from GitHub support.

**Comment by mlinksva** [comment]
@1138-4EB look at the output above:

> License: Other

Licensee is telling you that it sees two files with known licenses in them, but for the project it can't reach a conclusion. 

It special cases the situation in which there are two license files, one of them GPL and the other one is named COPYING.LESSER and contains LGPL. When that convention is followed, it can conclude LGPL for the project.

You can look in `lib/licensee/project/license_file.rb` and `lib/licensee/projects/project.rb` if you're interested in the code that does this.

**Comment by ale5000-git** [comment]
This is a feature request, why don't add an extra line like "Detected project license" where it say the final license in addition to the list of all licenses in the project?

From the current output someone that doesn't know LGPL cannot tell whether the project is GPL or LGPL licensed.

**Comment by ale5000-git** [comment]
Ok, now I understand but I think LICENSE.LESSER is more descriptive than COPYING.LESSER for non-Linux users.

Isn't possible to add also this please?

**Comment by 1138-4EB** [comment]
@mlinksva , thanks for the clarification. I will have a look at those files.

@ale5000-git, please, excuse me for pointing in the wrong direction.

**Comment by benbalter** [comment]
> Ok, now I understand but I think LICENSE.LESSER is more descriptive than COPYING.LESSER for non-Linux users.

It may be more descriptive, but it is contrary to [the license instructions](https://www.gnu.org/licenses/gpl-howto.en.html). If you believe projects should use `license.lesser`, you'll have to take that up with the publishers of the GPL. We simply implement their instructions (and should prefer consistency and ease of parsing over personal preference).

**Comment by ale5000-git** [comment]
@benbalter
As compromise if I put COPYING.LESSER on git as symlink to LICENSE.LESSER could it detect as it would be COPYING.LESSER and not as two separate licenses?

**Comment by ale5000-git** [comment]
Maybe an alternative would be to optionally have in the repository a file that list licenses, called for example "license.cfg" where every line contain a license (that can be one or more) with reference to license filenames (that can be one or more), like this:

LGPL-3.0-or-later=LICENSE.LESSER.rst;LICENSE.rst
Apache-2.0=APACHE.md

As:
[SPDX code of license 1]=[license 1 file 1];[license 1 file 2 if needed]
[SPDX code of license 2]=[license 2 file 1];[license 2 file 2 if needed]

Maybe it can be used just as hint for custom filenames.

**Comment by mlinksva** [comment]
Personally, I think it'd be OK to detect LGPL if COPYING and COPYING.LESSER exist with the right texts, or LICENSE and LICENSE.LESSER. We don't demand that GPL use COPYING so I don't object to analogous flexibility for the LGPL special case. The intent is pretty clear.

**Comment by ale5000-git** [comment]
@benbalter
In relation to the comment of @mlinksva is it possible to kindly change your mind about this or maybe doing a public survey about this thing to leave the majority choose?

**Comment by ale5000-git** [comment]
Also I think it would be more consistent to detect in a dynamic way using the existing license detection code rather than hardcoding it.

In this way:
```
whatever-license-name-is-already-detected-with extension-stripped.optional-ext
whatever-license-name-is-already-detected-with extension-stripped.LESSER.optional-ext
```

So if the code detect:
```
LICENSE
COPYING
FUTURE-LICENSE-NAME
```

then it automatically detect also:
```
LICENSE.LESSER
COPYING.LESSER
FUTURE-LICENSE-NAME.LESSER
```

**Comment by ale5000-git** [comment]
Bump.

**Comment by cbarrick** [comment]
Licensee is likely to return a false positive for the GPL when the actual license is the LGPL. This is a bug.

The point of using the LGPL is to support both free software and to allow the use of that software in proprietary applications. But a false positive for the GPL tells users that they *can't* use the software in a proprietary application. This explicitly contradicts the intent of the author and may cause downstream users to overlook an otherwise compatible library!

It's worth noting that nothing in the texts of the GPL or LGPL make any restriction on the file names. The GNU's instructions should therefore be considered advisory, not mandatory. However, the text of the GPL *does* require the LGPL amendments be distributed separately, i.e. the GPL states "Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed."

### Steps to reproduce a false positive:

1. A software author wishes to license her work under the LGPL.
2. She downloads [the official markdown files](https://www.gnu.org/licenses/lgpl-3.0.md) for both the GPL and the LGPL.
3. Per the GNU's instructions, she names the files `COPYING` and `COPYING.LESSER`.
4. Because the files are markdown, she appends the `.md` extension to both file names.
5. Licensee reports `GPL-3.0` rather than `LGPL-3.0` **with a confidence of 99.28%**, detecting `COPYING.md` but not `COPYING.LESSER.md`.

This scenario does not seem at all outrageous.

The crux of the issue is that the GPL can be detected from any file name, but the LGPL can only be detected from a single file name. Since the LGPL requires the text of the GPL to be present, Licensee has a high chance of only finding the GPL text and producing a false positive with very high confidence.

The solution is clear: be less strict about the naming of the LGPL file.

### A proposed solution

As far as I can tell, the rules for matching license file are to look for a few base names possibly followed by a single extension. Usually if Licensee finds two files that contradict themselves, it gives up, but if one of those files is the GPL (regardless of the file name) and the other file is the LGPL **and** that file is named `COPYING.LESSER` (case insensitive), then the LGPL wins.

I propose two changes. First, if two license files are found where one is the GPL and the other is the LGPL, the LGPL wins, *regardless of file name*. It is much less likely that a rouge LGPL file will be detected in a GPL codebase than it is for only the GPL to be found in an LGPL codebase. Second, license files should be allowed to contain multiple extensions. This allows for `COPYING.LESSER.md`.

For the first task, I think we could just eliminate the check on the file name in `LicenseFile.lgpl?`. I don't really know Ruby, buf AFAICT all the LGPL handling code in the `Project` class doesn't care about the name. (This makes the restriction on the file name feel particularly arbitrary.)

For the second task, I think we could just add a repetition to `OTHER_EXT_REGEX`.

**Comment by mlinksva** [comment]
Thanks for the info @cbarrick. I notice that `COPYING.LESSER.md` (not outrageous, but very rare) isn't treated as a license file at all by licensee. This is an oversight even if we didn't positively identify `LGPL-3.0` with a license name other than `COPYING.LESSER` (which as above I don't have a problem with doing).

**Comment by cbarrick** [comment]
Cool. I'll put together a PR with the changes I mentioned.

I've never written Ruby and have no idea about best practices, but the changes seem simple enough. Is there anything I should be aware of?

**Comment by ale5000-git** [comment]
Any update for this?

**Comment by ale5000-git** [comment]
Bump.

**Comment by ale5000-git** [comment]
Bump

**Comment by RedHoodedWraith** [comment]
If LGPL cannot be detected with Licensee, how do we manually configure our GitHub Repo to list the License as LGLv3.0 in the right sidebar?

**Comment by mlinksva** [comment]
@RedHoodedWraith LGPL can be detected with Licensee, it's just particular. Follow the instructions at https://choosealicense.com/licenses/lgpl-3.0/#how-to-apply

**Comment by ale5000-git** [comment]
Bump.

**Comment by ale5000-git** [comment]
@benbalter: Just try searching `COPYING` on Google and tell me if anyone can know what is without prior knownledge.

**Comment by NumesSanguis** [comment]
I just created a new repo and selected "GPLv3", which created a LICENSE file in my repo. Then I added an extra file, called it "LICENSE.LESSER" and copied the LGPLv3 contents in it. GitHub now indicates my repo as: `GPL-3.0, LGPL-3.0 licenses found `. 

I guess this means that licensee does detect LGPLv3 now even if it is called `LICENSE.LESSER`? Or could the `GPL-3.0` found part cause any issues when people filter on a license?
