### ISSUE TITLE
Is there a JS implementation of ContentHelper?

### ISSUE THREAD

**Issue by jeffmcaffer** [licensee/licensee#360]
We would like to use the license hashing algorithm in `ContentHelper` more broadly and in particular in a JavaScript environment for https://clearlydefined.io. Do you know if there is a JavaScript implementation? Would you be willing to host one as part of the licensee repo (so it stays in sync) or prefer that we add one in our own context?

**Comment by benbalter** [comment]
> Do you know if there is a JavaScript implementation?

Not that I know of. It grew out of necessity as we discovered various license normalization edge cases. You can pass a `--json` flag to the command line tool if shelling out is an option, and you'll get back machine readable output. Also glad to add a dedicated hashing command that could could pipe a string to if it would be helpful in your context?

> Would you be willing to host one as part of the licensee repo (so it stays in sync) or prefer that we add one in our own context?

I'm torn. On the one hand, I appreciate the efficiency in terms of shared tests, etc. On the other hand, it would mean any changes to ContentHelper would need to simultaneously implemented in javascript to keep the two in sync. Does the "sync" need to be to `master` or to a release?

As an alternative, would it make sense to move Licensee to its own org, with a Ruby repo, and javascript repo, and shared test fixtures (and their expected hashes) to simplify testing/updates?

**Comment by mlinksva** [comment]
The content hashing algorithm in `ContentHelper` is a byproduct of content normalization, which has been changed/improved many times and there's no reason to expect it to be stable. I wouldn't recommend using it if stability is a requirement. I never got around to expanding on my comment at https://github.com/benbalter/licensee/issues/328#issuecomment-415061608 but I'm not sure I see value of exposing an unstable hash at all and would recommend changing the public API to just an hash of the unmodified license content. If there's value in a hash of normalized license content for other applications, there should be a specification for a canonical normalization that can be relied upon to create a stable hash that could easily be implemented in multiple languages. Just offhand opinion, I may not understand the requirements of either licensee or clearlydefined here. 😄

**Comment by jeffmcaffer** [comment]
Thanks for the additional context. The point about stability is important. 

Our usecase is to enable multiple independent tools to be run on files to detect licenses and have a consistent set of identifiers for the licenses. SPDX has ids for 00s of licenses but there are 000s in the wild. Without something like this, each tool comes up with its own notion of identity for the license and users are left having to manage the relationship between them to do their license checks. Automated processing is stymied as tools can't tell if two licenses are the same or were just discovered by different tools.

Evolution in the hashing algorithm could perhaps be addressed by versioning the output. eg. ids from v1 or the algorithm would yield something like `licenseRef-v1-432bfe31` where v2 would be `licenseRef-v2-982fea32`. We would need a mapping table for equivalencies but we'd need that anyway to map eventual SPDX ids to prior hash values. IIRC this is essentially/effectively what you have done in Licensee.

There is no actual need to keep the Licensee and ClearlyDefined hashing algorithms in sync but we should also not needlessly diverge. The Licensee code seems small and deterministic so is a great starting point.

**Comment by mlinksva** [comment]
I don't think licensee or any users of licensee have versioned license content hash output, but yes that would work.

FWIW there's https://spdx.org/spdx-license-list/matching-guidelines many of which are applicable to licenses not cataloged by SPDX (ie do not operate on SPDX templates) which I imagine could be tightened so that it'd be easy for two implementations to produce same output (or maybe it's already there). There are implementations, or rather https://github.com/src-d/go-license-detector/blob/34b911eb872f308bebf331ef80df3623a63bf8de/licensedb/internal/normalize/normalize.go is one I recall, and @benbalter semi-recently implemented (#342) some of the SPDX matching guidelines in licensee (mixed with its own normalization). An old javascript implementation found with a quick search https://github.com/myndzi/spdx-license-matcher/blob/6a275ff99226001fa9fdde28abf50a9cd33e1e1a/normalize.js

**Comment by jeffmcaffer** [comment]
Indeed the normalization should implement the SPDX matching guidelines and potentially more (though if there are more it would be good to get that into the SPDX spec). The existence of Go and JS incantations of this function makes it feels even more like we should have multiple implementations working against the same rules and test data.

We could start doing this as part of ClearlyDefined proper as it fits reasonably in the domain/mandate, or do it somewhere else. SPDX is a potential home but they do not so a lot of tools and the normalization may need to advance out of step with the spec.

Thoughts? Would you all be interested in moving this code out to a shared place?

**Comment by mlinksva** [comment]
Makes sense to me to have a shared place with multiple implementations working against the same rules and test data.

**Comment by goneall** [comment]
There is also a Java implementation for license matching using the license matching guidelines in the [SPDX tools](https://github.com/spdx/tools).

**Comment by jeffmcaffer** [comment]
Sweet. Another one! I see it at https://github.com/spdx/tools/blob/master/src/org/spdx/compare/LicenseCompareHelper.java. Looks like it is part of the overall license matching implementation as you say. Could it be factored out do you think?

I wonder how different all these are. I suspect that some of the tools like ScanCode and FOSSology may have some similar logic (though they could use completely different matching approaches).

**Comment by goneall** [comment]
> Could it be factored out do you think?

From taking a quick look it would be a small to moderate amount of effort to refactor this out into its own utility.  The static helper class implements some text matching which doesn't have too many dependencies on the rest of the library.  Unfortunately the same class has a couple of functions which has quite a few dependencies.  If anyone is interested in using some specific functions without the rather heavy weight of the entire SPDX tools library, let me know and I'll look into it further.

> I wonder how different all these are. I suspect that some of the tools like ScanCode and FOSSology may have some similar logic (though they could use completely different matching approaches).

I've looked into some of the other compare algorithms and most of the implementations use algorithms which provide some type of score for how close the text matches rather than using the rules provided by the SPDX legal team.  The advantage of these other algorithms is that they are much faster than the rules based matching algorithm.  I wouldn't use the SPDX tools matching to search a large code base for possible license matches - it would just be too slow.  Within my own tools, I use a 2 pass approach for analyzing source code.  The first pass uses algorithms similar to ScanCode and FOSSology to identify possible matches and a second pass using the rules based approach.  If the rules approach matches, I feel confident declaring the licenses as a match even without human review.  Otherwise, a human looks at the match before determining if it is really a match or not.

**Comment by mlinksva** [comment]
I bet license matching is the expensive part. Template-agnostic license normalization ought be cheap, and probably possible to separate from matching. I don't think they are very intertwined in licensee anyway. Licensee only tries a somewhat expensive (but probably not nearly as expensive or accurate as leveraging the semantics of SPDX license XML/templates) similarity match for a text against candidate licenses if the text and candidate licenses, after normalization, are similar in length (so only a handful of candidates are actually tested).

I suspect they are separable from a specification as well -- in https://spdx.org/spdx-license-list/matching-guidelines the expensive matching part (as opposed to cheap pre-matching normalization) is mostly in 2. Substantive Text.
