### ISSUE TITLE
GNU "… or later" licenses are not detected

### ISSUE THREAD

**Issue by htgoebel** [licensee/licensee#406]
### Describe the bug

Github does not detect GNU "… or later" licenses, even if the repository clearly states this license applies.

### Steps to reproduce the behavior

1. Go to https://github.com/debops/yaml2rst/
2. Look at information line below the repository description and above the file listing - this is where the number of commits, branches, etc. are listed.
   -> At the right edge it says "GPL-3.0"
3. Verify the code actually uses GPL-3.0-or-later:
   1. Scroll down to the Readme. Near the top, it says "Licence: GNU General Public Licence v3 or later (GPLv3+)"
   2. Open the file [`setup.py`, scroll to line 39](https://github.com/debops/yaml2rst/blob/v0.3/setup.py#L39), which says: `GNU General Public License v3 or later (GPLv3+)'`
   3. Open the file [`yaml2rst/__main__.py`, scroll to line 12](https://github.com/debops/yaml2rst/blob/v0.3/yaml2rst/__main__.py#L12): The license header clearly states "or (at your option) any later version."
   4. You may verify the same in other files.

### Expected behavior

Github should detect the "or later" variant of the license and display "GPL-3.0-or-later" in the information line and in the repository meta data.

### Screenshots

![Screenshot_20200102_193625](https://user-images.githubusercontent.com/784161/71685120-a896fb00-2d97-11ea-8ac4-48dda0716672.png)

### Additional context

The same applies to other repositories, e.g.
* https://github.com/pytest-dev/unittest2pytest

**Comment by mlinksva** [comment]
I presume moved from https://github.com/github/choosealicense.com/issues/713

FWIW there are 3 distinct issues here:

- Licensee doesn't support Python package metadata. This would be easy to fix, just not as easy as the package metadata licensee presently supports, since Python package metadata for licenses doesn't standardize on SPDX identifiers and expressions (presumably a cost of being ahead on caring about license metadata at all? just a guess, I don't know the timeline) though maybe it will eventually https://github.com/python/peps/pull/1148
- Licensee doesn't recognize +/-or-later (nor -only) in package metadata. This would require more effort, as the way licensee works is currently closely tied to a set of canonical license texts...this would need to be extended, and would impact various places in the program, eg when package detection is turned on, for an overall conclusion to not be NOASSERTION, the license found in the license file and package metadata need to agree, but it would make sense for eg a GPL-3.0 license text and GPL-3.0-or-later package metadata to produce an overall conclusion of GPL-3.0-or-later
- github.com would have to utilize optional package metadata license detection, which might entail further requirements for licensee, but otherwise is out of scope for this repo

**Comment by htgoebel** [comment]
Is assume, there is another, more basic issue:

According to [what-we-look-at.md](https://github.com/licensee/licensee/v9.13.0/master/docs/what-we-look-at.md) Licensee looks at the `LICENSE` file. For GNU licenses, the license text always contains the term
> If the Program specifies […] “or any later version” applies to it, …

Thus detecting the license file is no sufficient to tell whether the project is licensed "-only" or "-later".  This needs to be specified elsewhere, e.g. in the Readme file or the meta-data.

**Comment by mlinksva** [comment]
@htgoebel exactly. That's why adding -or-later licenses to the choosealicense.com catalog (vendored here) doesn't help, as they are the same texts, and why the 3 issues I point out above all concern meta-data.
