### ISSUE TITLE
Apache license not detected

### ISSUE THREAD

**Issue by jupp0r** [licensee/licensee#414]
### Describe the bug

I have the problem that a license file in my repository is not recognized as Apache 2.0.

https://github.com/LogMeIn/asyncly/blob/master/LICENSE

### Steps to reproduce the behavior

1. Go to https://github.com/LogMeIn/asyncly/blob/master/LICENSE

### Expected behavior

Apache license info is shown.

**Comment by mlinksva** [comment]
The reason is the `COPYRIGHT` file in the repo which licensee identifies as potentially having license info but can't positively identify what license is being asserted. You could fix this by moving the file, perhaps to `debian/COPYRIGHT`? I realize that it is a DEP-5 file and that licensee could fix this by detecting candidates and parsing DEP-5 files, but this would require someone to implement that.

```
$ script/git-repo https://github.com/LogMeIn/asyncly/blob/master/LICENSE
License:        NOASSERTION
Matched files:  LICENSE, COPYRIGHT, Readme.md
LICENSE:
  Content hash:  ab3901051663cb8ee5dea9ebdff406ad136910e3
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       Apache-2.0
COPYRIGHT:
  Content hash:  3c336c8e8d377546090cb5e7d815c8e922791467
  License:       NOASSERTION
Readme.md:
  Content hash:  deef36d74d269e018e54609ad97ee0ec87891307
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       Apache-2.0
```

**Comment by BigBlueHat** [comment]
It does look like `debian/copyright` is the preferred location for this file regardless.
