### ISSUE TITLE
Prefer recognized license over unrecognized

### ISSUE THREAD

**Issue by laughinghan** [licensee/licensee#415]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

[My project](https://github.com/laughinghan/mechanical) is dual-licensed between [Blue Oak](https://blueoakcouncil.org/license/1.0.0), which Licensee understandably doesn't recognize, and MIT. I'd like GitHub to recognize my project as MIT licensed, but instead Licensee categorizes my project as "other"

### Describe the solution you'd like

I'd like Licensee to recognize that of the multiple licenses supported by my project, one of them is a recognized license, and use that as the matched license

### Describe alternatives you've considered

I could get what I want by renaming the `LICENSE-BlueOak.md` file to `LICENSE2-BlueOak.md`, so that the only file whose name starts with `LICENSE-` will be `LICENSE-MIT`. But trying to hide information from Licensee doesn't sound like the right approach, what if it the regexes change to recognize `LICENSE<number>` in the future? Licensee is already supposed to handle multi-licensed projects.

### Additional context

Even when you [view the `LICENSE-MIT` file on GitHub](https://github.com/laughinghan/mechanical/blob/master/LICENSE-MIT), it still doesn't show that it's recognized, even though I copied the text verbatim from GitHub's own https://choosealicense.com:

![Screen Shot 2020-03-12 at 14 23 28](https://user-images.githubusercontent.com/225809/76571866-d07c9c00-6475-11ea-8fd1-c16e50bfdfec.png)

Contrast:

![Screen Shot 2020-03-12 at 14 31 02](https://user-images.githubusercontent.com/225809/76571879-d83c4080-6475-11ea-91e8-2c26e2bc06ae.png)

**Comment by mlinksva** [comment]
> I'd like GitHub to recognize my project as MIT licensed, but instead Licensee categorizes my project as "other"

The first part of what I just wrote in https://github.com/licensee/licensee/issues/416#issuecomment-601476960 also applies to this issue: This would be contrary to licensee's conservative project license identification. Only if every indicator it looks at detects the same license, it returns NOASSERTION: it errs on the side of false negative rather than false positive.

> Licensee is already supposed to handle multi-licensed projects

It does, but only the overall conclusion for a project is used in the GitHub UI. Here's the output from the command line:

```
$ script/git-repo https://github.com/laughinghan/mechanical
License:        NOASSERTION
Matched files:  LICENSE-BlueOak.md, LICENSE-MIT, package.json
LICENSE-BlueOak.md:
  Content hash:  f275153a1c897ee662738001a014b480205d2265
  License:       NOASSERTION
  Closest non-matching licenses:
    BSD-4-Clause similarity:  28.92%
LICENSE-MIT:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) The Mechanical Community
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
package.json:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::NpmBower
  License:     NOASSERTION
```

Regarding the last bit, licensee also doesn't understand SPDX license expressions. It'd be great if it did, but that would be a big feature addition.

> Even when you view the LICENSE-MIT file on GitHub, it still doesn't show that it's recognized, even though I copied the text verbatim from GitHub's own https://choosealicense.com

This isn't an issue with licensee. I'll pass your feedback about GitHub on, although I'm afraid I can't promise if or when it'll be addressed.
