### ISSUE TITLE
Command-line option to match a given file

### ISSUE THREAD

**Issue by jhansche** [licensee/licensee#433]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

I have a project to compile reports of all 3rd party dependency licenses. I'm able to extract all of the license files/names/URLs etc, but as of now, the only way to get the tool to detect the license of that file is by putting it into its own directory and naming it `LICENSE`.

### Describe the solution you'd like

Currently `licensee detect [PATH]` works if the path is a directory containing a LICENSE (etc) file, or if the path **is** directly to a file named LICENSE.

The proposed solution would treat a case where `[PATH]` points a single file, the same as if it had been discovered as a LICENSE file. For example:

```
$ ls output/deps/
com.example.artifact1.lic
com.github.artifact2.lic
$ licensee detect output/deps/com.example.artifact1.lic
License:        Apache-2.0
Matched files:  output/deps/com.example.artifact1.lic
LICENSE:
  Content hash:  ab3901051663cb8ee5dea9ebdff406ad136910e3
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       Apache-2.0
```

### Describe alternatives you've considered

Current workaround is to create a separate directory for every dependency, and place the output into a single file named `LICENSE`, and then run the detection against that file or directory.  Using above example:

```
$ mkdir output/deps/com.example.artifact1/
$ mv output/deps/com.example.artifact1.lic output/deps/com.example.artifact1/LICENSE
$ licensee detect output/deps/com.example.artifact1/          # WORKS
$ licensee detect output/deps/com.example.artifact1/LICENSE   # Also WORKS
```

This works, but significantly changes the structure and requirements, for what appears to be arbitrary reasons.

**Comment by mlinksva** [comment]
I'd use this feature and suspect it could be implemented in https://github.com/licensee/licensee/blob/master/lib/licensee/projects/fs_project.rb (check whether path is a file rather than a directory, use that file if so).

**Comment by jhansche** [comment]
Any reason not to keep this open?

**Comment by mlinksva** [comment]
@jhansche nobody's working on it, so stalebot closed it.

I'd be OK with exempting `good-first-issue` (which can be hard to come by) and maybe `help-wanted` labels in https://github.com/licensee/licensee/blob/5b5e6aca3aad34e57f9d8e6a71abe2c48a896e36/.github/stale.yml#L12-L14 but that'd be up to @benbalter and as that file notes would need to be changed in Ben's .github repo (though I'm not certain that's the case now given licensee moved to its own org).

In any case you or anyone should feel free to submit a PR to address this request even though the issue is closed as stale. 😄
