### ISSUE TITLE
Regression: BSD 3-clause no longer recognized

### ISSUE THREAD

**Issue by wnbittle** [licensee/licensee#454]
### Describe the bug

The BSD 3-clause license is no longer being recognized.

### Steps to reproduce the behavior

Please see my repo here https://github.com/dyn4j/dyn4j and the LICENSE.md

### Expected behavior

The license is detected as BSD 3-clause

### Screenshots

N/A

### Additional context

This was working as of a week or two ago so it appears to be a regression.  I've tried to match the license content and format exactly (apart from name and years), but this did not seem to help.

**Comment by mlinksva** [comment]
If you run `dos2unix` on your LICENSE.md, commit, and push, it should be recognized.

Something about CRLF is causing `all rights reserved` to not be normalized from your LICENSE.md, and causes it to fall just below threshold for recognition. This is a bug.

There must have been a change in `lib/licensee/content_helper.rb` at some point since #205 that introduced a subtle bug that didn't trigger the test added there. I'll look into it when I have a chance, but other investigation/fix is welcome!

**Comment by mlinksva** [comment]
I noticed there are `\n`s in some regexes so rather than figure out what edge case this is hitting, the safe thing to do seemed to be to just convert all line endings, so that's what's in #455.

@wnbittle it'll probably be some time before there's a new release of licensee and that is deployed on github.com, though as I wrote above, you should be able to get your repo's license detected by pushing a version with LF newlines.

**Comment by wnbittle** [comment]
Thank you for the quick response and good find with the line endings.  I've changed to LF and it appears to be working now.
