### ISSUE TITLE
File other than license starting with word license as prefix doesn't get recognized

### ISSUE THREAD

**Issue by jcs090218** [licensee/licensee#457]
### Describe the bug

When there is one other file with word `license` as prefix. The repository cannot recognize the license file type. For example, I have a repository [jcs-elpa/license-templates](https://github.com/jcs-elpa/license-templates). I have `license-template.el` file then the bar on the right shows `View license` even thought that GitHub are able to find the `LICENSE.txt` file.

But if I removed the file, the `LICENSE.txt` file can be recognized like the screenshot image shown below.

![91514444-5e135180-e919-11ea-89de-b1081761ead4](https://user-images.githubusercontent.com/8685505/92220463-a2c95a80-eece-11ea-85ca-8081af1030e4.png)

### Steps to reproduce the behavior

1. Create a repository.
2. Commit one find with real license file `LICENSE.txt` and another file with the word `license` as prefix.
3. You will be able to see `View license` in the bar on the right.

### Expected behavior

If licensee are able to find the file `LICENSE.txt` (when you click on `View license`). The license file should still able to recognized. In this scenario, it should be `GPL-3.0 License`.

**Comment by mlinksva** [comment]
It's kid of by design. Licensee is conservative, favoring false negatives over false positives. It should be very clear that a file with the word license (or similar) isn't intended to contain a license, but what's easy for a human to see is not for licensee. There's a similar report in #425 that I think has a high enough confidence fix in #443.

I suppose we could conceivably exclude more file extensions, or even the word 'template' in the filename, but either seems _really_ specific. I guess we've done something similar once before in #256.
