### ISSUE TITLE
LICENSE is not detected for repository when other files named `license-checks.xml` and `license_test.go` exist

### ISSUE THREAD

**Issue by gm3dmo** [licensee/licensee#479]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.
Problem: Repository License is not being reliably detected in a file named LICENSE in cases where other files named license exist.

Organizations with large numbers of open source repositories such as [googleapis](https://github.com/googleapis) have placed their license in a file named `LICENSE` at the root of their repository. 

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

### Describe the solution you'd like
Have a check which finds LICENSE (all uppercase) and if found does not evaluate further files or introduced them for making a decision about the type of license.

### Additional context

 Renaming or removing files named `license_test.go`, `license-checks.xml` is not a practical solution for large numbers of open source reposotories where organizations want to have their open source software's license be detectable by the GitHub license API.

**Comment by mlinksva** [comment]
I don't think licensee should take the solution you'd like. It prefers false negatives to false positives, and there are lots of repos with multiple license files of various names that are in fact license files applying to something in the repos for which it may be incorrect to make an assertion based on just one of them.

However it probably makes sense to exclude `.xml` and `.go` extensions as such files are very unlikely to contain license texts.

Looking at https://github.com/googleapis it appears that all on the first page are identified as Apache-2.0. I found a couple examples though, https://github.com/googleapis/java-channel/ has `license-check.xml` (looks like 100 of 470 repos in the org may have that file) and https://github.com/googleapis/google-api-go-client has `license_test.go` (2 of 470).

**Comment by JustinBeckwith** [comment]
Greetings - to give a little context on how I got here - I opened a support case with GitHub, because the [License API](https://docs.github.com/en/rest/reference/repos#get-a-repository) was returning the incorrect license for many of our repositories (notably, the ones that had other files in the root with `license` in the name).  I don't know the relationship between this gem and GitHub's API other than they use it, but I just wanted to shine a light on the actual problem I'm running into :)

**Comment by mlinksva** [comment]
Thanks @JustinBeckwith. GitHub uses this gem, but there will be a lag between a fix being pushed to the default branch here, a release being cut, and that release being used on GitHub.

I accidentally pushed 9cd4ddd968e90a07309eca9bb118601247924f3d rather than opening a PR and can't force push to the default branch, and pushing a revert for the purpose of opening a PR seems unnecessary. Happy to make further changes if implementation could be better, as I'm sure it could cc @benbalter 😅
