### ISSUE TITLE
bsd 3 clause licence tweak not being picked up 

### ISSUE THREAD

**Issue by exussum12** [licensee/licensee#493]
### Describe the bug

It seems reasonably common in php repos to change the third clause from "the licence holder" with the author's name. This stops the licence being picked up. 

### Steps to reproduce the behavior

1. Get a wording 3 clause licence. 
2. Change the words "the licence holder" to a person's name 
3. Notice the licence is no longer picked up  

### Expected behavior

Not 100% sure if this is a valid change to a bsd 3 licence. 

### Additional context

This seems reasonably common in the php ecosystem to make this tweak. Not sure if it happens in other languages too .

**Comment by mlinksva** [comment]
2. Do you mean "the copyright holder"? "the license holder" doesn't appear.
3. Could you point out an example or two? Links would be more useful than screenshots.

**Comment by exussum12** [comment]
Ive started putting PR's on to fix them but yeah heres some links
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/licence.txt
https://github.com/getsentry/sentry-php/blob/master/LICENSE
https://github.com/sebastianbergmann/phpunit/blob/master/LICENSE

**Comment by mlinksva** [comment]
Thanks @exussum12. The current version of licensee successfully detects BSD-3-Clause for PHP_CodeSniffer and sentry-php. Typically license detection won't be attempted again on github.com unless a change to a license file in the repo has been pushed (these haven't changed in awhile), or you may be able to contact support and get them to trigger a re-detection.

Substituting for values like copyright holder in the body of license texts definitely makes detection more fragile, so thanks for encouraging people to use unmodified license texts. ✨ 

The current version of licensee doesn't detect BSD-3-Clause for phpunit, probably because its LICENSE file begins with "phpunit". Licensee has a hard time dealing with random text before an expected copyright line. Hmm, perhaps it could lookahead a bit more for a copyright line, and still penalize for random text (which increases uncertainty) but not get thrown off of finding and normalizing the copyright line. 🤔

**Comment by andreas-hakansson-ingka** [comment]
I'm using github.com/github/licenced and, the way I've understood things, it uses licensee to parse license information. I've been testing it out on a Go project and I've also noticed that there are several BSD-3-Clause files that it does not seem to identify correctly

Here are some examples
- https://github.com/google/go-cmp/blob/master/LICENSE
- https://github.com/protocolbuffers/protobuf-go/blob/master/LICENSE

**Comment by mlinksva** [comment]
@andreas-hakansson-ingka I'm not sure for the examples you provide that it's a licensee issue. Current licensee (and whatever versions were deployed in 2017 and 2019 when the first and last LICENSE files were pushed) correctly detects BSD-3-Clause for go-cmp and compress. The protobuf-go LICENSE file is also correctly detected, but the overall result for the repo is NOASSERTION due to the presence of a PATENTS file.
