### ISSUE TITLE
Common gems (activerecord, pg) not being detected properly (GitHub action environment)

### ISSUE THREAD

**Issue by jensljungblad** [licensee/licensee#530]
### Describe the bug

Common gems are labeled `other` instead of `mit`.

### Steps to reproduce the behavior

Using the https://github.com/github/licensed gem, but understood that this is the library that is actually doing the license detection.

Using a standard Rails app (6.1.4.4), running the following commands in a GitHub action environment:
```
bundle exec licensed cache
bundle exec licensed status
```

Results in a lot of cache entries labeled `other` instead of i.e. `mit`. Some examples:

```
Errors:
* app.bundler.activerecord
  filename: /app/.licenses/bundler/activerecord.dep.yml, version: 6.1.4.4, license: other, allowed: false
    - license needs review: other

* app.bundler.bcrypt
  filename: /app/.licenses/bundler/bcrypt.dep.yml, version: 3.1.16, license: other, allowed: false
    - license needs review: other

* app.bundler.elasticsearch
  filename: /app/.licenses/bundler/elasticsearch.dep.yml, version: 7.6.0, license: other, allowed: false
    - license needs review: other

* app.bundler.pg
  filename: /app/.licenses/bundler/pg.dep.yml, version: 1.3.1, license: other, allowed: false
    - license needs review: other
```

### Expected behavior

I would expect `activerecord` to be labeled `mit`, same as `activemodel`, `activejob` etc. The cache entries themselves look *very* similar, not sure why `activerecord` gets mislabeled.

### Additional context

Verified on multiple local systems and also in a GitHub action.

**Comment by benbalter** [comment]
@jensljungblad I suspect that while annoying in practice, many of these cases will be cases where licensee intentionally chooses not to make an assertion. 

There are instructions in [the contributing documentation](https://github.com/licensee/licensee/blob/master/docs/CONTRIBUTING.md#reporting-an-improperly-detected-license) on how to debug undetected licenses, but looking at `bcrypt` as an example with the `licensee diff` command, (`licensee diff https://github.com/bcrypt-ruby/bcrypt-ruby --remote --license mit`), I see:

```
{+- coda hale <coda.hale@gmail.com> c implementation of the bcrypt algorithm by+}
{+solar designer and placed in the public domain. jbcrypt is copyright (c) 2006+}
{+damien miller <djm@mindrot.org>.+}
```

Since Licensee has no way of knowing if that additional text is legally significant (in this case, it may be, since part of the code is public domain and part is MIT), it properly fails to recognize the project as MIT licensed.

**Comment by jensljungblad** [comment]
I'll try the `diff` command, thanks! I thought it seemed strange that `activerecord` was not detected but every other Rails package was, for instance. Such as `activejob`, `activemodel` and so on. Their licenses looked identical at a first glance. I'll try checking it with the debug commands.
