### ISSUE TITLE
Suggestion: Vendor the latest tag from the SPDX license list rather than the latest commit

### ISSUE THREAD

**Issue by goneall** [licensee/licensee#540]
### Describe the bug

More of a suggestion to consider rather than a bug.

The SPDX license list main branch is updated with in-progress changes.  Prior to release, all of the changes are reviewed by the SPDX legal team.  There are (somewhat rare) situations where a license XML file may be changed after the initial commit and prior to a release.  Released versions are considered more stable than the in-progress main branch.

Releases are tagged with the release version.

### Steps to reproduce the behavior

This is based on a review of the [vendor-spdx file](https://github.com/licensee/licensee/blob/master/script/vendor-spdx).  It appears to pull the latest from main.

### Expected behavior

Pull from the latest tag.

### Additional information

This [stack-overflow article](https://stackoverflow.com/questions/1404796/how-can-i-get-the-latest-tag-name-in-current-branch-in-git) provides a suggestion on how to identify the latest tag.

**Comment by mlinksva** [comment]
I'd rather not do this, though I appreciate where it is coming from. Reasons:

- I try to direct people to contribute to spdx/license-list-XML at every opportunity as that will benefit the community most, and has the most eyes on it. Delaying uptake of such contributions lowers incentive to go that path.
- The risk of any significant (to licensee's detections) change being reversed by the legal team seems very, very low, in part because (well by my casual observation) several members of that team have their eyes on license-list-XML PRs; I can't recall such a situation ever, though I may have not been paying close enough attention.

**Comment by goneall** [comment]
@mlinksva Your reasons for not making this change sense to me.

I'll go ahead and close the issue.

Thanks for considering the suggestion.
