### ISSUE TITLE
License section in README.md preferred over real license

### ISSUE THREAD

**Issue by TheJJ** [licensee/licensee#555]
### Describe the bug

When the repo README.md has a `## License` section, it is preferred over a 100% match in `LICENSE`.
Tested with `licensee (9.15.2)`.
Probably related to #553 and #554.

### Steps to reproduce the behavior

- have an new directory with two files:
  - GPL-3 license text in `LICENSE`
  - `README.md` with this content:
```
# Test
## License
```
when licensee is run, it reports:
```
License:        NOASSERTION
Matched files:  LICENSE, README.md
LICENSE:
  Content hash:  7d4cdf499d39e2e1ce27b2878e22872f0f5a74dd
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-3.0
README.md:
  Content hash:  da39a3ee5e6b4b0d3255bfef95601890afd80709
  License:       NOASSERTION
  Closest non-matching licenses:
    Zlib similarity:   0.00%
    WTFPL similarity:  0.00%
    Vim similarity:    0.00%
```

### Expected behavior

It should detect GPL-3 instead of NOASSERTION.

**Comment by mlinksva** [comment]
Licensee doesn't prefer README to LICENSE, rather it does not make an assertion if it encounters any license signal that it can't interpret -- you'd get the same result with a README it could detect, and a LICENSE it could not. Possibly the README matcher should be made fuzzier than it is, though a blank license section in a README would still obtain noassertion.

On github.com README detection is not enabled. The reason https://github.com/SFTtech/starlit-emacs says "View License" rather than "GPL-3.0" is that it has COPYING and LICENSE files, and the former's contents aren't the GPL-3.0 license text. Conceivably licensee could be made to treat standard header content (which may be what's in COPYING, I didn't look super closely) as at least supporting material for positively identifying a license if found alongside the appropriate license text.
