### ISSUE TITLE
Not all Markdown licenses are checked

### ISSUE THREAD

**Issue by jgcodes2020** [licensee/licensee#577]
### Describe the bug

Not all Markdown licenses from https://github.com/IQAndreas/markdown-licenses are recognized 

### Steps to reproduce the behavior

1. See https://github.com/jgcodes2020/tas-input-qt

### Expected behavior
GitHub should recognize as LGPL 3. The license was copied verbatim from the above repository.

**Comment by mlinksva** [comment]
Detecting markdownified licenses is pretty fragile but there may be ways to improve. I've created #578 to explore.

Regarding https://github.com/IQAndreas/markdown-licenses/blob/66202b51f3cfa74d8008e395f89d403a7f5a27ed/gnu-lgpl-v3.0.md the reasons for not matching are at least
- it removes periods from headings I would strongly discourage adding or removing any characters that will be displayed or not for stylistic reasons; licensee has no way of knowing which are significant
- it adds markdown bullets probably to get expected indentation where bullets aren't used in the original; this is not quite as bad as adding/removing characters, and it's possible licensee's markdown processing could be improved to ignore this

**Comment by benbalter** [comment]
In https://github.com/licensee/licensee/pull/374, we added support for the opposite... converting HTML files to Markdown, so that they can be detected. Markdown formatting _should_ be stripped, as not legally significant, assuming no other changes to the text. 

One alternate approach would be to render all Markdown as HTML, and then strip HTML tags. This would in theory give us the substantive text without formatting markup.

**Comment by mlinksva** [comment]
Interesting idea @benbalter. Makes me think Redcarpet's StripDown renderer might get us there without round trip.

**Comment by Hans5958** [comment]
I would like to point out that I also can't find the licenses on https://github.com/idleberg/Creative-Commons-Markdown working. When I changed it so it uses the usual non-Markdown license, it works.

**Comment by mlinksva** [comment]
Thanks @Hans5958. I added the 3 CC licenses licensee currently can detect to tests in #578 so that those will be covered if/when this is eventually fixed. CC0-1.0 https://github.com/idleberg/Creative-Commons-Markdown is already detected. CC-BY[-SA]-4.0 from that repo aren't probably mostly due to the "considerations" links which I suppose could be normalized when found in markdown.

**Comment by mlinksva** [comment]
Fixed in the PRs referenced above.
