### ISSUE TITLE
License not detected for BSD 2-Clause

### ISSUE THREAD

**Issue by sstallion** [licensee/licensee#613]
### Describe the bug

This afternoon I updated the license text for some changes to an older repository by updating the copyright year: https://github.com/sstallion/go-hid/blob/master/LICENSE. After making the change, the LICENSE file is no longer detected as a 2-clause BSD license. What is especially strange is I have an identical license in another repository that is detected correctly: https://github.com/sstallion/dynamic-motd/blob/master/LICENSE

### Steps to reproduce the behavior

1. Go to https://github.com/sstallion/go-hid/
2. Click on the licenses link to the right
3. Notice the type for LICENSE is marked as Unknown

### Expected behavior

The LICENSE should be identified as a 2-Clause BSD license.

### Screenshots

N/A

### Additional context

N/A

**Comment by mlinksva** [comment]
It looks like your identical license in another repository is actually at https://github.com/sstallion/dynamic_motd/blob/master/LICENSE (with - instead of _ I get 404) and also is not detected. The reason is copyright holder(s)->author. That's a small change but there isn't much text in BSD-2-Clause and that's enough to push to barely under threshold of 98 for a match.

```wdiff
% bundle exec licensee diff https://github.com/sstallion/dynamic_motd --remote --license bsd-2-clause
Comparing to BSD 2-Clause "Simplified" License:
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Input Length:      1209
License length:    1230
Similarity:      97.58%
diff --git a/LICENSE b/LICENSE
index b779518..e913995 100644
--- a/LICENSE
+++ b/LICENSE
@@ -4,13 +4,13 @@ of source code must retain the above copyright notice, this list of conditions
and the following disclaimer. - redistributions in binary form must reproduce
the above copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the distribution. this
software is provided by the [-copyright holders-]{+author+} and contributors 'as is' and any express or
implied warranties, including, but not limited to, the implied warranties of
merchantability and fitness for a particular purpose are disclaimed. in no event
shall the [-copyright holder-]{+author+} or contributors be liable for any direct, indirect, incidental,
special, exemplary, or consequential damages (including, but not limited to,
procurement of substitute goods or services; loss of use, data, or profits; or
business interruption) however caused and on any theory of liability, whether in
contract, strict liability, or tort (including negligence or otherwise) arising
in any way out of the use of this software, even if advised of the possibility
of such damage.
```
I'd consider this a bug that is fixable -- the reason I vendored SPDX license-list-xml templates in #477 was to eventually (no promises of when, still) add more matching flexibility based on the annotations in those templates, including exactly the changed words in your license text, see https://github.com/licensee/licensee/blob/58915065487166a407814354e65fffce2390fbac/vendor/license-list-XML/src/BSD-2-Clause.xml#L30-L33

However for now if you want your license to be detected you'll have to stick more exactly to the default text.

**Comment by sstallion** [comment]
Hi @mlinksva - thanks for the quick response. I suspected it was something along those lines. The license text for both projects is taken verbatim from the FreeBSD Software License Policy, which is the originator of the 2-clause BSD license: https://www.freebsd.org/internal/software-license/.  I've noticed that some versions of the license have been changing the language recently, which is at the root of the issue.

I'd prefer to not change the licenses themselves given that I've used the same text for over twenty years now and is required by the FreeBSD project for external submissions.

Do you have a rough idea of when this could be addressed? It seems to be a recent change as these projects have been correctly identified as 2-clause until now. I'd be happy to submit a patch, but I might need a bit of guidance.

**Comment by mlinksva** [comment]
Thanks for the report @sstallion and that's a compelling point that the version specified by the FreeBSD project isn't detected. I added a test and made a very slight tweak in #617 that seems to fix this bug without waiting for a more thorough solution (which may be fairly involved and I'm not sure when I'll have time for).

Tangentially:
> I've noticed that some versions of the license have been changing the language recently, which is at the root of the issue

I can't think of any recent changes, though "recent" for BSD could be many years ago. @bsdimp has been contributing over in https://github.com/spdx/license-list-XML where a number of variations of BSD licenses are cataloged. That's generally the best place to account for or even correct changes these days that will eventually ripple elsewhere (including here).

**Comment by sstallion** [comment]
Fair enough - thanks a bunch for the help!

**Comment by bsdimp** [comment]
FreeBSD and all the BSDs really have been generating variations on the BSD license since 1993... The vast majority of them aren't in the SPDX database... BSD licenses weren't the focus of the OSI (opensourse.org) so they picked just the original license from Berkeley, but with changes... but none of the variations...  SPDX inherited this bias and tried to clean up the mess, but only got so far... the vast majority of the variations, by my finger in the air, haven't been cataloged (though they mostly trigger a close match for the ones I've used the matching tools for). Most are grammar or silly word changes... most likely aren't legally significant but that hasn't been reviewed yet.  The first in file ones though may need new variations...

however, the only changes in the last two years have been to match more licenses... so I'm not sure why matching stopped working
