### ISSUE TITLE
zlib LICENSE file is not detected as the zlib license

### ISSUE THREAD

**Issue by AlexMax** [licensee/licensee#799]
### Describe the bug

[zlib](https://github.com/madler/zlib) is not being detected as using the eponymous [zlib license](https://en.wikipedia.org/wiki/Zlib_License).

### Steps to reproduce the behavior

Navigate to the zlib repository and note that the [LICENSE](https://github.com/madler/zlib/blob/develop/LICENSE) file is not detected as the zlib license.

### Expected behavior

LICENSE should be detected as the zlib license, as in [this example](https://github.com/libsdl-org/SDL/blob/main/LICENSE.txt).

### Additional context

There's a joke to be made, but I'm too lazy to think of one. 😄

**Comment by mlinksva** [comment]
Joke worthy indeed. It's not being detected due to the prefix

```
Copyright notice:

```

and the trailer:

```
  Jean-loup Gailly        Mark Adler
  jloup@gzip.org          madler@alumni.caltech.edu
```

before and after the expected license text. I've not seen either pattern before, but it's a big world of ~LICENSE files. The prefix would be easy to account for in licensee (but that would not be enough for detection), the trailer possible but difficult (I guess lookahead for something that looks like signatures and remove from candidate text if they are aligned with what's in the copyright line?) out of proportion to the benefit of detecting this one instance. However, feel free to make a PR or further comment if this is really important to you.

I note https://github.com/spdx/license-list-XML/blob/cb00a23b3b52d7cb20f5f3d2d69ff40c13f9c7f0/src/Zlib.xml doesn't include either the prefix or trailer. Given how common zlib is I wonder what other tools including those using the license-list-XML dataset are doing?

Also perhaps ironically I noticed a problem with matching against the original Zlib license (I may have been confused) in https://github.com/spdx/license-list-XML/issues/529 but apparently not concerning the prefix and trailer elements!
